
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-bz

pool:
 vmImage: 'ubuntu-16.04'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
  displayName: Use Python 3.6

- bash: |
    echo "##vso[task.prependpath]/data/anaconda/bin"
  displayName: Add Conda to PATH

- script: 
     python scripts/generate_conda_file.py --gpu
  displayName: ' generate_conda_file.py'

#- bash: |
#    ls
#    cd scripts
#    ls
#    which -a conda
#  displayName: 'ls'
  

#    cd Recommenders
# chg root
#- bash: | 
#   conda update conda -n base
#   enable: false
# displayName: 'create conda env1'

#- script: | 
#     conda install -c conda conda-env
#  displayName: 'create conda env2'

#import os before importing

- script: |
    conda env create --yes --quiet --name reco_gpu --file ./reco_gpu.yaml 
  displayName: 'create conda env3'

- task: PythonScript@0
  inputs:
    targetType: 'inline'
    script: |
      print('Hello world 1')
      print('Hello world 2')
  displayName: ' Python Script'
  
- bash: |
    conda env list
    source activate reco_gpu
    pytest --version
#    python -c "import azureml.core; print("SDK version:", azureml.core.VERSION)"
#    pytest tests/unit/test_gpu_utils.py::test_get_number_gpus
  displayName: 'unit tests'

#- task: PythonScript@0:
##  inputs:
#    targetType: 'inline'
#    script:
#      ws = Workspace(subscription_id = 15ae9cb6-95c1-483d-a0e3-b1a1a3b06324, resource_group = 'recommender', workspace_name = 'RecoWS')
#    echo "$BUILD_REPOSITORY_LOCALPATH"
#    ls

#  displayName: ' set up ws'

#- script: 
#     python scripts/AzureDevOps.py
#  displayName: ' test_aml_compute'

