# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-bz

pool:
 name: 'RecommendersAgentPool'
 vmImage: 'RecoLinuxAgentGPU'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: |
    echo "##vso[task.prependpath]/data/anaconda/bin"
  displayName: Add Conda to PATH

- bash: |
    echo "##vso[task.prependpath]/data/anaconda/bin"
  displayName: Add Conda to PATH

- bash: |
    conda create -q -n reco python=3.5 -y
    conda env update -q -n reco -f image_classification/environment.yml
  displayName: 'Conda install dependencies'

- bash: |
    source activate reco
    cd image_classification
    pytest tests/unit --junitxml=junit/test-unitttest.xml
  displayName: 'tests'
