# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-bz

pool:
 name: 'RecommendersAgentPool'
 vmImage: 'RecoLinuxAgentGPU'

steps:

- bash: |
    echo "##vso[task.prependpath]/data/anaconda/bin"
  displayName: Add Conda to PATH


- bash: |
    scripts/generate_conda_file.py
    conda create -q -n reco_base python=3.5 -y
  displayName: 'Conda create reco_base env'

- bash: |
    source activate reco_base
    pytest tests/unit --junitxml=junit/test-unitttest.xml
  displayName: 'unit tests'
